sudo: required
services:
  - docker
before_install:
  # docker upgrade
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker build -t abesesr/clamscan-docker:fortravis image/
  - docker run -d --rm --name clamscan-docker -v /tmp/data/:/folder-to-scan/ -e SCAN_AT_STARTUP="1" abesesr/clamscan-docker:fortravis
  - docker ps
  - sleep 20 && docker logs clamscan-docker
script:
  # 1st test: 1 running container?
  - NB_CONTAINERS=$(docker ps | grep " Up " | wc -l)
  - test $NB_CONTAINERS = 1
  # 2nd test: clamscan-docker well scan the given folder
  - test $(docker logs suspicious_goldwasser | grep "SCAN SUMMARY") = "----------- SCAN SUMMARY -----------"
