sudo: required
services:
  - docker
before_install:
  # docker upgrade
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker build -t abesesr/clamscan-docker:fortravis image/
  # download and unzip a virus (juste for tests !)
  - curl https://raw.githubusercontent.com/ytisf/theZoo/master/malwares/Binaries/Win32.LuckyCat/Win32.LuckyCat.zip > /tmp/Win32.LuckyCat.zip
  - cd /tmp/ && unzip -P infected ./Win32.LuckyCat.zip
  # run clamscan on this folder
  - docker run -d --rm --name clamscan-docker -v /tmp/:/folder-to-scan/ -e SCAN_AT_STARTUP="1" -e CRON_CLAMSCAN="0 0 * * *" -e SMTP_HOST="" -e SMTP_PORT="" abesesr/clamscan-docker:fortravis
  - docker ps
  - sleep 20 && docker logs clamscan-docker
script:
  # 1st test: 1 running container?
  - NB_CONTAINERS=$(docker ps | grep " Up " | wc -l)
  - test $NB_CONTAINERS = 1
  # 2nd test: clamscan-docker well scan the given folder
  - test "$(docker logs clamscan-docker | grep 'SCAN SUMMARY')" = '----------- SCAN SUMMARY -----------'
  # 3rd test: clamscan-docker well detect the virus (1 file)
  - test "$(docker logs clamscan-docker | grep 'Infected files' | grep '1')" != ''
  
  
