# This docker-compose.yml can be used as a usage example
# it is also used for clamscan-docker developements

version: '3'

services:


  clamav:
    build: ./image/
    image: abesesr/clamscan-docker:1.4.0
    container_name: clamav
    environment:
      FRESHCLAM_AT_STARTUP: "1"
      SCAN_AT_STARTUP: "1"
      SCAN_ONLY_NEW_FILES: "1"
      FOLDER_TO_SCAN: "/folder-to-scan/"
      CRON_CLAMSCAN: "0 * * * *"
      CLAMSCAN_OPTIONS: "--recursive=yes --allmatch=yes --remove=no --suppress-ok-results"
      ALERT_MAILTO: "security@team.fr"
      SMTP_TLS: "off"
      SMTP_HOST: "clamav-mailhog"
      SMTP_PORT: "1025"
    depends_on:
      - clamav-mailhog
    volumes:
      - ./volumes/folder-to-scan/:/folder-to-scan/


  clamav-mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: clamav-mailhog
    environment:
      MH_SMTP_BIND_ADDR: "0.0.0.0:1025" # cf https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
    ports:
      - 8025:8025
    logging:
      driver: none
