name: "clamscan-docker docker image"

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    


    - name: Setup tmate session (debug)
      uses: mxschmitt/action-tmate@v3
    
    
    - name: Build the Docker image
      run: docker build ./image/ --tag abesesr/clamscan-docker:latest


    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./image/
        push: ${{ github.event_name != 'pull_request' }}
        tags: abesesr/clamscan-docker:latest
        
